### ISSUE TITLE
Please don't forget this module

### ISSUE THREAD

**Issue by cecnull1** [gengyoubo/MCSE#1]
This issue is not really an issue; it's just a reminder for the developers. Feel free to delete this issue once you've taken note of it

**Comment by gengyoubo** [comment]
我很忙的，又要开发整合包，又要做模组。不要发无关的评论。

**Comment by cecnull1** [comment]
知道，毕竟假期快到了，急很正常

**Comment by gengyoubo** [comment]
我没有假期......,然后有什么事情在QQ里聊。
